"use strict";
let fname;
let lname;
fname = "John";
lname = "Doe";
let fname2;
fname2 = fname.toUpperCase();
console.log(fname2, lname);
let age;
age = 26.5;
let boo;
boo = (age > 20);
console.log(boo);
let arr;
arr = [1, 2, 3, 4, 5];
let newarr;
newarr = arr.filter((num) => num > 2);
console.log(newarr);
let c = 2 /* Color.Blue */;
